---
# Variables used in tasks:
# - openwrt_config_files (list of dict)

- name: Copy files
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "root"
    group: "root"
    mode: "{{ item.mode }}"
  loop: "{{ openwrt_config_files }}"
  when: openwrt_config_files is defined
